version: '3'
services:
  tasks:
    build:
      context: .
      dockerfile: Dockerfile.tasks

    command: /var/app/tasks-start.sh --processes 1
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/app
    environment:
      - ORIGIN_DOMAIN=localhost:2222
      - REDIS_URL=redis://redis:1111
    ports:
      - "2222:2222"
  redis:
    image: "redis:alpine"
    command: --port 1111
    ports:
      - "1111:1111"
    expose:
      - "1111"

  web:
      build:
        context: .
        dockerfile: Dockerfile.web
      stdin_open: true
      tty: true
      ports:
        - "127.0.0.1:3333:5000"
      volumes:
        - ./:/var/app